version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    networks:
      - backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src

  db:
    container_name: ${POSTGRES_DB}
    image: postgres
    networks:
      - backend
    ports:
      - '5433:5432'


    volumes:
      - data:/data/db

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  data: {}

networks:
  backend:

